/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./src/context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  List: { // root type
    id: number; // Int!
    title: string; // String!
  }
  Mutation: {};
  Query: {};
  Task: { // root type
    id: number; // Int!
    position: number; // Int!
    status: boolean; // Boolean!
    title: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  List: { // field return type
    id: number; // Int!
    tasklist: NexusGenRootTypes['Task'][]; // [Task!]!
    title: string; // String!
  }
  Mutation: { // field return type
    createList: NexusGenRootTypes['List']; // List!
    createTask: NexusGenRootTypes['Task']; // Task!
    moveTask: NexusGenRootTypes['Task'] | null; // Task
    updateTask: NexusGenRootTypes['Task'] | null; // Task
  }
  Query: { // field return type
    getList: NexusGenRootTypes['List'] | null; // List
    getLists: NexusGenRootTypes['List'][]; // [List!]!
    getTask: NexusGenRootTypes['Task'] | null; // Task
    getTasks: NexusGenRootTypes['Task'][]; // [Task!]!
  }
  Task: { // field return type
    id: number; // Int!
    position: number; // Int!
    status: boolean; // Boolean!
    title: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  List: { // field return type name
    id: 'Int'
    tasklist: 'Task'
    title: 'String'
  }
  Mutation: { // field return type name
    createList: 'List'
    createTask: 'Task'
    moveTask: 'Task'
    updateTask: 'Task'
  }
  Query: { // field return type name
    getList: 'List'
    getLists: 'List'
    getTask: 'Task'
    getTasks: 'Task'
  }
  Task: { // field return type name
    id: 'Int'
    position: 'Int'
    status: 'Boolean'
    title: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createList: { // args
      title: string; // String!
    }
    createTask: { // args
      listid: number; // Int!
      title: string; // String!
    }
    moveTask: { // args
      newListId?: number | null; // Int
      newPosition: number; // Int!
      taskid: number; // Int!
    }
    updateTask: { // args
      newStatus?: boolean | null; // Boolean
      newTitle?: string | null; // String
      taskid: number; // Int!
    }
  }
  Query: {
    getList: { // args
      id: number; // Int!
    }
    getTask: { // args
      id: number; // Int!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}